### PR TITLE
Fix import query parsing

### LINKED ISSUE #250: WP_MySQL_Token::get_value() throws error when importing wp_aioseo_notifications SQL query
When I import the SQL file that contains the `wp_aioseo_notifications` table dump in Studio, the SQLite driver throws the error.

Steps to reproduce:

1. Create Studio site
2. Import the SQL file that contains the `wp_aioseo_notifications` table dump

Error:

```
Uncaught TypeError: WP_MySQL_Token::get_value(): Return value must be of type string, null returned
```

### LINKED ISSUE #263: Failed to parse the MySQL query error
When importing a WordPress MySQL dump, I’m getting an error when executing `wp sqlite import dump.sql`, which parses the file into multiple queries and then calls `driver->query($statement)` for each statement. The SQLite import command is parsing the query incorrectly, and then the SQLite driver throws an error.

I wonder if there is a built-in parser in the SQLite plugin or if we could pass and execute multiple statements together instead of one by one.

Here is the related code:

https://github.com/Automattic/wp-cli-sqlite-command/blob/main/src/Import.php#L53-L54

**Example Query:**

```
/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `wp_redirection_404` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `url` mediumtext NOT NULL,
  `domain` varchar(255) DEFAULT NULL,
  `agent` varchar(255) DEFAULT NULL,
  `referrer` varchar(255) DEFAULT NULL,
  `http_code` int(11) unsigned NOT NULL DEFAULT 0,
  `request_method` varchar(10) DEFAULT NULL,
  `request_data` mediumtext DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created` (`created`),
  KEY `referrer` (`referrer`(191)),
  KEY `ip` (`ip`)
) ENGINE=InnoDB AUTO_INCREMENT=280033 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `wp_redirection_404` (`id`, `created`, `url`, `domain`, `agent`, `referrer`, `http_code`, `request_method`, `request_data`, `ip`) VALUES (279314,'2025-09-26 08:45:02','/\\\"https:\\/\\/sejas.blog\\/newsletter\\/\\','https://sejas.blog','Mozilla/5.0 (compatible; FeedDiscovery/1.0; +https://example.com/bot)',NULL,404,'GET',NULL,'127.0.0.1');
```

**Error**

```
PHP Fatal error:  Uncaught WP_SQLite_Driver_Exception: Failed to parse the MySQL query. in /wordpress/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php:5035
Stack trace:
#0 /wordpress/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(672): WP_SQLite_Driver->new_driver_exception('Failed to parse...')
#1 /tmp/sqlite-command/src/Import.php(54): WP_SQLite_Driver->query('INSERT INTO `wp...')
#2 /tmp/sqlite-command/src/Import.php(38): Automattic\WP_CLI\SQLite\Import->execute_statements('studio-backup-s...')
#3 /tmp/sqlite-command/src/SQLite_Command.php(45): Automattic\WP_CLI\SQLite\Import->run('studio-backup-s...', Array)
#4 [internal function]: Automattic\WP_CLI\SQLite\SQLite_Command->import(Array, Array)
#5 /tmp/sqlite-command/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 /tmp/sqlite-command/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(497): call_user_func(Object(Closure), Array, Array)
#8 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(470): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#9 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(493): WP_CLI\Runner->run_command(Array, Array)
#10 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(136): WP_CLI\Runner->run_command_and_exit()
#11 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1349): WP_CLI\Runner->do_early_invoke('after_wp_config...')
#12 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
#13 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(84): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(35): WP_CLI\bootstrap()
#16 phar:///tmp/wp-cli.phar/php/boot-phar.php(20): include('phar:///tmp/wp-...')
#17 /tmp/wp-cli.phar(4): include('phar:///tmp/wp-...')
#18 /tmp/run-cli.php(25): require('/tmp/wp-cli.pha...')
#19 {main}
  thrown in /wordpress/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 5035

    at JetpackImporter.importDatabase (/Applications/Studio.app/Contents/Resources/app.asar/dist/main/index.js:14371:17)
    at async JetpackImporter.import (/Applications/Studio.app/Contents/Resources/app.asar/dist/main/index.js:14411:9)
    at async importBackup (/Applications/Studio.app/Contents/Resources/app.asar/dist/main/index.js:15754:12)
    at async importSite (/Applications/Studio.app/Contents/Resources/app.asar/dist/main/index.js:16207:20)
    at async Session.<anonymous> (node:electron/js2c/browser_init:2:107024)
```

### PR DESCRIPTION
**Pull request by JanJakes**
### Description:
This is a quick fix of import query parsing, replacing https://github.com/Automattic/wp-cli-sqlite-command/pull/13 for now. It adds multiple fixes and improvements that make the query recognition in the input dump almost complete.

The only known edge cases that aren't supported yet are the usage of `NO_BACKSLASH_ESCAPES` SQL mode, and the MySQL `DELIMITER ...` statement. We likely won't implement those in the current logic—it's better to make the new query tokenizer fully support streaming to handle all edge cases correctly.

### Related issues:
- Fixes STU-844.
- Fixes https://github.com/WordPress/sqlite-database-integration/issues/263.
- Fixes https://github.com/WordPress/sqlite-database-integration/issues/250.

### Testing Instructions

* Create a blank site using Studio
* It doesn't matter if the site is running or not.
* Edit the file `~/Library/Application Support/Studio/server-files/sqlite-command/src/Import.php` with the changes from this PR.
* In Studio go to the Import/Export tab
* Try multiple queries like those provided on STU-844 or https://github.com/WordPress/sqlite-database-integration/issues/250, or [wp_redirection_404_with-create-table.sql](https://github.com/user-attachments/files/22771369/wp_redirection_404_with-create-table.sql)
* Confirm that the SQL files are imported correctly.
* Try importing the same SQL dump and confirm that an alert appears stating that "Create Table" couldn't be executed. This is expected because you already imported that dump and created the table.
* Feel free to try other sites and queries to confirm everything works as expected.

### CODE REVIEW

**Review by sejas — APPROVED** [review]
@JanJakes, thanks for improving the WP-CLI parser.
I tested it with the two problematic SQL dumps, and both were executed correctly 🥳

It makes the import process a bit slower. Similarly to #13, it increases the import time by ~50%.
I tested it by importing a single 60MB SQL dump file which took 27 seconds compared to 18 seconds with the previous parser. I think the increase is due to checking the encoding. Maybe we could try executing the query as it is, which will work in most scenarios and if the query fails, we could then check the encoding of the statement.

The good part of streaming the file is that we don't reach the memory limit, and I was able to import a big site.

cc @wojtekn

**Comment by sejas** [comment]
>  I tested it by importing a single 60MB SQL dump file which took 27 seconds compared to 18 seconds with the previous parser.

@JanJakes I've created this PR using your branch as base. It keeps the same speed during the import because it converts the encoding only if the execution fails. Could you review it?
- https://github.com/Automattic/wp-cli-sqlite-command/pull/15

**Review by sejas — APPROVED** [review]

**Comment by JanJakes** [comment]
@sejas @wojtekn This seems to be done and approved. I'm not sure if I should merge, so please, go ahead anytime.

**Comment by sejas** [comment]
Thank you @JanJakes ! @wojtekn will take another look and after that I'll merge it and create a new wp-cli sqlite release and close STU-844 and other issues.

File: src/Import.php [hunk 1]
```diff
@@ -51,10 +51,21 @@ public function run( $sql_file_path, $args ) {
...
-			$result = $this->driver->query( $statement );
-			if ( false === $result ) {
-				WP_CLI::warning( 'Could not execute statement: ' . $statement );
-				echo $this->driver->get_error_message();
+			try {
+				$this->driver->query( $statement );
+			} catch ( Exception $e ) {
+				try {
+					// Try converting encoding and retry
+					$detected_encoding = mb_detect_encoding( $statement, mb_list_encodings(), true );
```
Comment (wojtekn) [inline src/Import.php:59]: Would it be safer and more reliable to detect encoding based on initial part of the file e.g. a few kilobytes and then if it differs, convert it for all statements?

**Review by wojtekn — APPROVED** [review]
I left one comment.

Besides that, it works as expected - all my test imports, along with problematic queries, work fine.

File: src/Import.php (hunk 1 above)
Comment (JanJakes) [reply src/Import.php:59]: Or, zooming out, is there a better way to detect and fix encoding earlier in the process, e.g., using Node.js? The problem with `mb_detect_encoding` is that it's not very reliable: https://www.php.net/manual/en/function.mb-detect-encoding.php

Screenshot 2025-10-10 at 14 53 12

Comment (sejas) [reply src/Import.php:59]: Reading only the first bytes doesn't identify the correct encoding. We need to read the whole file at once or statement by statement.

Reading the encoding in Node.js and passing it as an argument to WP-CLI sqlite could be a solution. For efficiency, I'll merge and release this PR, and we can consider future improvements if necessary.
